name: ornitho_veryrare_DE

on:
  workflow_dispatch:

jobs:
  ornitho_veryrare_DE-post:
    runs-on: macos-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ORNITHO_BOT: ${{ secrets.ORNITHO_BOT }}
      ORNITHO_USER: ${{ secrets.ORNITHO_USER }}
      ORNITHO_PW: ${{ secrets.ORNITHO_PW }}
      CHAT_ID: ${{ secrets.CHAT_ID }}
      
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install telegram.bot package
        run: Rscript -e 'install.packages("telegram.bot", dependencies = TRUE)'
      - name: Install rvest package
        run: Rscript -e 'install.packages("rvest", dependencies = TRUE)'
      - name: Install xml2 package
        run: Rscript -e 'install.packages("xml2", dependencies = TRUE)'
      - name: Install safer package
        run: Rscript -e 'install.packages("safer", dependencies = TRUE)'
      - name: Create and save file
        run: Rscript ornitho_veryrare_DE.R

      - name: Commit files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          git commit -am "add data"
          git push 
